[env:lolin32_lite]
platform = espressif32
board = lolin32_lite
framework = arduino
monitor_speed = 115200
upload_speed = 57600
board_build.partitions = partitions.csv
build_flags =
  -D SMART_SUP_VERSION=\"0.1.0\"
build_src_filter =
  +<main.cpp>
  -<imu_i2c_scan.cpp>
  -<imu_yb_probe.cpp>
lib_deps =
  adafruit/Adafruit AHRS@^2.4.0

[env:imu_i2c_scan]
extends = env:lolin32_lite
build_flags =
  -D SMART_SUP_VERSION=\"imu-i2c-scan\"
build_src_filter =
  +<imu_i2c_scan.cpp>
  -<main.cpp>

[env:imu_yb_probe]
extends = env:lolin32_lite
build_flags =
  -D SMART_SUP_VERSION=\"imu-yb-probe\"
build_src_filter =
  +<imu_yb_probe.cpp>
  -<main.cpp>
  -<imu_i2c_scan.cpp>
