[env:lolin32_lite]
platform = espressif32
board = lolin32_lite
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.partitions = partitions.csv
extra_scripts = pre:set_version.py
build_src_filter =
  +<main.cpp>
  -<imu_i2c_scan.cpp>
  -<imu_yb_probe.cpp>
lib_deps =
  adafruit/Adafruit AHRS@^2.4.0

[env:imu_i2c_scan]
extends = env:lolin32_lite
build_src_filter =
  +<imu_i2c_scan.cpp>
  -<main.cpp>

[env:imu_yb_probe]
extends = env:lolin32_lite
build_src_filter =
  +<imu_yb_probe.cpp>
  -<main.cpp>
  -<imu_i2c_scan.cpp>
