[env:lolin32_lite]
platform = espressif32
board = lolin32_lite
framework = arduino
monitor_speed = 115200
upload_speed = 57600
board_build.partitions = partitions.csv
build_flags =
  -D SMART_SUP_VERSION=\"0.1.0\"
lib_deps =
  adafruit/Adafruit AHRS@^2.4.0
