[platformio]
default_envs = receiver_esp32, remote_esp32c3

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
upload_speed = 460800
build_flags =
  -D ESPNOW_TEST_CHANNEL=1

[env:receiver_esp32]
board = lolin32_lite
build_src_filter =
  +<receiver_main.cpp>

[env:remote_esp32c3]
board = esp32-c3-devkitm-1
upload_protocol = esptool
build_src_filter =
  +<remote_main.cpp>
build_flags =
  ${env.build_flags}
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D ESPNOW_RECEIVER_MAC=\"40:22:D8:3B:E8:04\"
