package com.smartsup.controller.model

data class Telemetry(
    val batteryVoltage: Float? = null,
    val leftCurrent: Float? = null,
    val rightCurrent: Float? = null,
    val escTemperature: Float? = null,
    val imuAvailable: Boolean? = null,
    val ybImuAvailable: Boolean? = null,
    val headingDegrees: Float? = null,
    val ybHeadingDegrees: Float? = null,
    val targetHeadingDegrees: Float? = null,
    val ybAccelXG: Float? = null,
    val ybAccelYG: Float? = null,
    val ybAccelZG: Float? = null,
    val ybGyroZRadS: Float? = null,
    val ybMagXUt: Float? = null,
    val ybMagYUt: Float? = null,
    val ybMagZUt: Float? = null,
    val ybImuCalibrationState: Int? = null,
    val ybMagCalibrationState: Int? = null,
    val ybQuatW: Float? = null,
    val ybQuatX: Float? = null,
    val ybQuatY: Float? = null,
    val ybQuatZ: Float? = null,
    val ybRollDegrees: Float? = null,
    val ybPitchDegrees: Float? = null,
    val ybYawDegrees: Float? = null,
    val leftOutputPercent: Int? = null,
    val rightOutputPercent: Int? = null,
    val statusFields: Map<String, String> = emptyMap(),
    val controllerMessage: String = "等待连接",
    val lastSentCommand: String = "--",
    val lastReceivedStatus: String = "--",
)
